Project:      output/time_test
Build Number: 0
Date:         Tue Mar 13 11:40:24 2012
Compiler:     ICCM8C
Version:      7.05.00


Area                               Addr   Size   Decimal Bytes (Attributes)
--------------------------------   ----   ----   ------- ----- ------------
                             lit   01A0   02A9 =    681. bytes (rel,con,rom,lit)

       Addr  Global Symbol
      -----  --------------------------------
       01CC  LoadConfigTBL_time_test_Bank0
       026D  LoadConfigTBL_time_test_Bank1
       02D4  __ctype
       0449  __lit_end

Area                               Addr   Size   Decimal Bytes (Attributes)
--------------------------------   ----   ----   ------- ----- ------------
                        func_lit   0449   0042 =     66. bytes (rel,con,rom,proclab)

       Addr  Global Symbol
      -----  --------------------------------
       0449  __func_lit_start
       048B  __func_lit_end

Area                               Addr   Size   Decimal Bytes (Attributes)
--------------------------------   ----   ----   ------- ----- ------------
                     psoc_config   048B   0167 =    359. bytes (rel,con,rom,code)

       Addr  Global Symbol
      -----  --------------------------------
       048B  LoadConfigTBL_time_test_Ordered
       0590  _LoadConfigInit
       0590  LoadConfigInit
       0597  _LoadConfig_time_test
       0597  LoadConfig_time_test
       05F2  __psoc_config_end

Area                               Addr   Size   Decimal Bytes (Attributes)
--------------------------------   ----   ----   ------- ----- ------------
                     UserModules   05F2   040A =   1034. bytes (rel,con,rom,code)

       Addr  Global Symbol
      -----  --------------------------------
       05F2  _TX8_1_ISR
       05F3  TX8_1_EnableInt
       05F3  _TX8_1_EnableInt
       05F7  _TX8_1_DisableInt
       05F7  TX8_1_DisableInt
       05FB  TX8_1_SetTxIntMode
       05FB  _TX8_1_SetTxIntMode
       060D  _TX8_1_Start
       060D  TX8_1_Start
       0612  _TX8_1_Stop
       0612  TX8_1_Stop
       0616  TX8_1_SendData
       0616  _TX8_1_SendData
       0619  _TX8_1_bReadTxStatus
       0619  TX8_1_bReadTxStatus
       0619  _bTX8_1_ReadTxStatus
       0619  bTX8_1_ReadTxStatus
       062C  _TX8_1_PutSHexByte
       062C  TX8_1_PutSHexByte
       063F  _TX8_1_PutSHexInt
       063F  TX8_1_PutSHexInt
       0646  _TX8_1_PutChar
       0646  TX8_1_PutChar
       064E  TX8_1_PutString
       064E  _TX8_1_PutString
       0660  TX8_1_Write
       0660  _TX8_1_Write
       0688  _TX8_1_CWrite
       0688  TX8_1_CWrite
       06B0  TX8_1_CPutString
       06B0  _TX8_1_CPutString
       06C2  _TX8_1_PutCRLF
       06C2  TX8_1_PutCRLF
       06CB  _Timer16_2_EnableInt
       06CB  Timer16_2_EnableInt
       06CF  Timer16_2_DisableInt
       06CF  _Timer16_2_DisableInt
       06D3  _Timer16_2_Start
       06D3  Timer16_2_Start
       06D7  Timer16_2_Stop
       06D7  _Timer16_2_Stop
       06DB  Timer16_2_WritePeriod
       06DB  _Timer16_2_WritePeriod
       06E1  _Timer16_2_WriteCompareValue
       06E1  Timer16_2_WriteCompareValue
       06E7  _Timer16_2_wReadCompareValue
       06E7  wTimer16_2_ReadCompareValue
       06E7  Timer16_2_wReadCompareValue
       06E7  _wTimer16_2_ReadCompareValue
       06ED  wTimer16_2_ReadTimerSaveCV
       06ED  _wTimer16_2_ReadTimerSaveCV
       06ED  wTimer16_2_ReadCounter
       06ED  Timer16_2_wReadTimerSaveCV
       06ED  _wTimer16_2_ReadCounter
       06ED  _Timer16_2_wReadTimerSaveCV
       0723  _Timer16_2_wReadTimer
       0723  _wTimer16_2_ReadTimer
       0723  _wTimer16_2_CaptureCounter
       0723  Timer16_2_wReadTimer
       0723  wTimer16_2_CaptureCounter
       0723  wTimer16_2_ReadTimer
       072B  _Timer16_1_ISR
       072F  Timer16_1_EnableInt
       072F  _Timer16_1_EnableInt
       0733  _Timer16_1_DisableInt
       0733  Timer16_1_DisableInt
       0737  _Timer16_1_Start
       0737  Timer16_1_Start
       073B  _Timer16_1_Stop
       073B  Timer16_1_Stop
       073F  _Timer16_1_WritePeriod
       073F  Timer16_1_WritePeriod
       0745  _Timer16_1_WriteCompareValue
       0745  Timer16_1_WriteCompareValue
       074B  _Timer16_1_wReadCompareValue
       074B  wTimer16_1_ReadCompareValue
       074B  _wTimer16_1_ReadCompareValue
       074B  Timer16_1_wReadCompareValue
       0751  wTimer16_1_ReadTimerSaveCV
       0751  Timer16_1_wReadTimerSaveCV
       0751  _Timer16_1_wReadTimerSaveCV
       0751  _wTimer16_1_ReadCounter
       0751  _wTimer16_1_ReadTimerSaveCV
       0751  wTimer16_1_ReadCounter
       0787  _Timer16_1_wReadTimer
       0787  Timer16_1_wReadTimer
       0787  wTimer16_1_CaptureCounter
       0787  _wTimer16_1_CaptureCounter
       0787  wTimer16_1_ReadTimer
       0787  _wTimer16_1_ReadTimer
       078F  _PWM8_2_EnableInt
       078F  PWM8_2_EnableInt
       0793  _PWM8_2_DisableInt
       0793  PWM8_2_DisableInt
       0797  _PWM8_2_Start
       0797  PWM8_2_Start
       079B  _PWM8_2_Stop
       079B  PWM8_2_Stop
       079F  _PWM8_2_WritePeriod
       079F  PWM8_2_WritePeriod
       07A2  PWM8_2_WritePulseWidth
       07A2  _PWM8_2_WritePulseWidth
       07A5  _bPWM8_2_ReadPulseWidth
       07A5  PWM8_2_bReadPulseWidth
       07A5  _PWM8_2_bReadPulseWidth
       07A5  bPWM8_2_ReadPulseWidth
       07A8  _bPWM8_2_ReadCounter
       07A8  bPWM8_2_ReadCounter
       07A8  PWM8_2_bReadCounter
       07A8  _PWM8_2_bReadCounter
       07D5  _PWM8_1_ISR
       07D6  _PWM8_1_EnableInt
       07D6  PWM8_1_EnableInt
       07DA  _PWM8_1_DisableInt
       07DA  PWM8_1_DisableInt
       07DE  PWM8_1_Start
       07DE  _PWM8_1_Start
       07E2  _PWM8_1_Stop
       07E2  PWM8_1_Stop
       07E6  _PWM8_1_WritePeriod
       07E6  PWM8_1_WritePeriod
       07E9  PWM8_1_WritePulseWidth
       07E9  _PWM8_1_WritePulseWidth
       07EC  PWM8_1_bReadPulseWidth
       07EC  _PWM8_1_bReadPulseWidth
       07EC  _bPWM8_1_ReadPulseWidth
       07EC  bPWM8_1_ReadPulseWidth
       07EF  _bPWM8_1_ReadCounter
       07EF  _PWM8_1_bReadCounter
       07EF  PWM8_1_bReadCounter
       07EF  bPWM8_1_ReadCounter
       081C  _PWM16_1_ISR
       0820  PWM16_1_EnableInt
       0820  _PWM16_1_EnableInt
       0824  _PWM16_1_DisableInt
       0824  PWM16_1_DisableInt
       0828  _PWM16_1_Start
       0828  PWM16_1_Start
       082C  PWM16_1_Stop
       082C  _PWM16_1_Stop
       0830  PWM16_1_WritePeriod
       0830  _PWM16_1_WritePeriod
       0836  _PWM16_1_WritePulseWidth
       0836  PWM16_1_WritePulseWidth
       083C  _wPWM16_1_ReadPulseWidth
       083C  wPWM16_1_ReadPulseWidth
       083C  PWM16_1_wReadPulseWidth
       083C  _PWM16_1_wReadPulseWidth
       0842  _wPWM16_1_ReadCounter
       0842  PWM16_1_wReadCounter
       0842  wPWM16_1_ReadCounter
       0842  _PWM16_1_wReadCounter
       087C  _PGA_1_SetPower
       087C  PGA_1_SetPower
       087C  PGA_1_Start
       087C  _PGA_1_Start
       088E  PGA_1_SetGain
       088E  _PGA_1_SetGain
       08B8  _PGA_1_Stop
       08B8  PGA_1_Stop
       08BC  _DigBuf_1_ISR
       08C0  DigBuf_1_EnableInt
       08C0  _DigBuf_1_EnableInt
       08C4  DigBuf_1_DisableInt
       08C4  _DigBuf_1_DisableInt
       08C8  DigBuf_1_Start
       08C8  _DigBuf_1_Start
       08CC  _DigBuf_1_Stop
       08CC  DigBuf_1_Stop
       08D0  AMUX4_1_InputSelect
       08D0  _AMUX4_1_InputSelect
       08EB  AMUX4_1_Start
       08EB  _AMUX4_1_Start
       08EC  AMUX4_1_Stop
       08EC  _AMUX4_1_Stop
       08ED  _ADCINC_1_ADConversion_ISR
       095B  ADCINC_1_Start
       095B  _ADCINC_1_Start
       096A  ADCINC_1_SetPower
       096A  _ADCINC_1_SetPower
       097C  ADCINC_1_Stop
       097C  _ADCINC_1_Stop
       0986  ADCINC_1_GetSamples
       0986  _ADCINC_1_GetSamples
       09AF  _ADCINC_1_StopADC
       09AF  ADCINC_1_StopADC
       09C3  ADCINC_1_fIsDataAvailable
       09C3  _ADCINC_1_fIsDataAvailable
       09C9  _ADCINC_1_iClearFlagGetData
       09C9  _ADCINC_1_wClearFlagGetData
       09C9  ADCINC_1_wClearFlagGetData
       09C9  ADCINC_1_iClearFlagGetData
       09D9  ADCINC_1_bClearFlagGetData
       09D9  ADCINC_1_cClearFlagGetData
       09D9  _ADCINC_1_bClearFlagGetData
       09D9  _ADCINC_1_cClearFlagGetData
       09E2  _ADCINC_1_iGetData
       09E2  ADCINC_1_wGetData
       09E2  ADCINC_1_iGetData
       09E2  _ADCINC_1_wGetData
       09EA  ADCINC_1_bGetData
       09EA  _ADCINC_1_bGetData
       09EA  _ADCINC_1_cGetData
       09EA  ADCINC_1_cGetData
       09F0  _ADCINC_1_fClearFlag
       09F0  ADCINC_1_fClearFlag
       09F9  _ADCINC_1_WritePulseWidth
       09F9  ADCINC_1_WritePulseWidth
       09FC  __UserModules_end

Area                               Addr   Size   Decimal Bytes (Attributes)
--------------------------------   ----   ----   ------- ----- ------------
                            text   09FC   127C =   4732. bytes (rel,con,rom,code)

       Addr  Global Symbol
      -----  --------------------------------
       09FC  _main
       09FC  __text_start
       0C5E  _m_test
       0D73  _My_gpio_p2_6
       0D84  _My_t16_1_isr
       0D95  _My_16_pwm_isr
       0DA6  _My_t16_2
       0DA9  _MyGpioISR_pwm
       0DBA  _adc_read
       0E06  _left
       0E10  _right
       0E1A  _stop
       0E22  _cur_read
       0F7F  _my_tx
       0FBA  _TxZeroTerminatedRamString
       0FCA  _led_t
       0FDC  _led2_t
       0FEE  _led_on
       0FFD  _led_off
       100C  _p0_3_on
       101B  _p0_3_off
       102A  _p0_5_on
       1039  _p0_5_off
       1048  _ReadADCChannel
       1102  _send_results
       11DC  _crlf
       1200  _dir_l
       1212  _dir_r
       1224  PSoC_GPIO_ISR
       12DE  __plcall
       12EA  _itoa
       14C3  _utoa
       1606  _isdigit
       1627  _islower
       1648  _isspace
       1669  _toupper
       16A7  __csdepi
       16D9  _csprintf
       1742  __cprint
       1C78  __xidata_start
       1C78  __text_end
       1C82  __xidata_end

Area                               Start  End    Decimal Bytes (Attributes)
--------------------------------   ----   ----   ------- ----- ------------
                             TOP   0000   0140 =    320. bytes (abs,ovr,rom,code)

       Addr  Global Symbol
      -----  --------------------------------
       0068  __Start
       013D  _bGetPowerSetting
       013D  bGetPowerSetting

Area                               Addr   Size   Decimal Bytes (Attributes)
--------------------------------   ----   ----   ------- ----- ------------
                    InterruptRAM   0000   0008 =      8. bytes (rel,con,ram)

       Addr  Global Symbol
      -----  --------------------------------
       0000  NO_SHADOW
       0000  _ADCINC_1_iResult
       0000  ADCINC_1_iResult
       0000  _NO_SHADOW
       0004  ADCINC_1_fStatus
       0004  _ADCINC_1_fStatus
       0005  _ADCINC_1_bState
       0005  ADCINC_1_bState
       0006  _ADCINC_1_fMode
       0006  ADCINC_1_fMode
       0007  ADCINC_1_bNumSamples
       0007  _ADCINC_1_bNumSamples

Area                               Addr   Size   Decimal Bytes (Attributes)
--------------------------------   ----   ----   ------- ----- ------------
               virtual_registers   0085   0009 =      9. bytes (rel,con,ram)

       Addr  Global Symbol
      -----  --------------------------------
       0085  __rZ
       0086  __rY
       0087  __rX
       0088  __r5
       0089  __r4
       008A  __r3
       008B  __r2
       008C  __r1
       008D  __r0

Area                               Addr   Size   Decimal Bytes (Attributes)
--------------------------------   ----   ----   ------- ----- ------------
                            data   0000   00CC =    204. bytes (rel,con,ram)

       Addr  Global Symbol
      -----  --------------------------------
       0000  __data_start
       0008  _vdiff_t
       0049  _rot_time
       005D  _rot_time1
       0071  _b
       007B  _a
       008E  _AsciiString
       0095  _tempf1
       0099  _temp_l
       009D  _tempf
       00A1  _temp2
       00A5  _ADCResult0
       00A7  _ADCResult
       00A9  _q
       00AB  _p_i
       00AD  _ADCResult3
       00AF  _ADCResult2
       00B1  _ADCResult1
       00B3  _iData
       00B5  _rot_count
       00B7  _vstart
       00B9  _temp0
       00BB  _temp1
       00BD  _temp3
       00BF  _vdi
       00C3  _vdiff
       00C5  _flag1
       00C6  _cr
       00C7  _rc
       00C8  _flag
       00C9  _vset
       00CA  _vsetv
       00CB  _tx_tim
       00CC  _Port1Shadow
       00CD  _results
       00CE  _pwm_val
       00CF  _test
       00D0  _vlf
       00D1  _s
       00D2  _cur_tx
       00D3  _vd
       00D4  _j
       00D5  _m_started
       00D6  _Channel
       00D7  _d
       00D8  _r
       00D9  _x
       00DA  _pwm2
       00DB  _i
       00DC  _vout

Files Linked      [ module(s) ]

./obj/boot.o	[ boot.asm ]
./obj/main.o	[ main.c ]
<library>	[ tx8_1int.asm, tx8_1.asm, timer16_2.asm, timer16_1int.asm, timer16_1.asm, pwm8_2.asm, pwm8_1int.asm ]
[ pwm8_1.asm, pwm16_1int.asm, pwm16_1.asm, psocgpioint.asm, psocconfigtbl.asm, psocconfig.asm ]
[ pga_1.asm, digbuf_1int.asm, digbuf_1.asm, amux4_1.asm, adcinc_1int.asm, adcinc_1.asm, rZ.asm ]
[ rY.asm, rX.asm, r5.asm, r4.asm, r3.asm, r2.asm, r1.asm, r0.asm, divmodu_16x16_16_util.asm, divmodu_32x32_32_util.asm ]
[ i_div16_block_util.asm, i_div32_block_util.asm, plcall.s, itoa.s, utoa.s, isdigit.s, islower.s ]
[ isspace.s, ctype.s, toupper.s, sprintf.s, _printf.s ]

Area Definitions

-blit:0x1a0.0x7fff
-bdata:0.0x6ff
-BInterruptRAM:0	allocated at: 0
-Bvirtual_registers	allocated at: 0x85
-Btime_test_RAM	allocated at: 0
-rwh:SSCParmBlk:0xf7.0xff

