//*****************************************************************************
//*****************************************************************************
//  FILENAME: DigBuf_1.h
//  Version: 1.3, Updated on 2012/3/2 at 9:14:31
//  Generated by PSoC Designer 5.2.2551
//
//  DESCRIPTION: DigitalBuffers User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2012. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef DigBuf_1_INCLUDE
#define DigBuf_1_INCLUDE

#include <m8c.h>

#pragma fastcall16 DigBuf_1_EnableInt
#pragma fastcall16 DigBuf_1_DisableInt
#pragma fastcall16 DigBuf_1_Start
#pragma fastcall16 DigBuf_1_Stop

//-------------------------------------------------
// Prototypes of the DigBuf_1 API.
//-------------------------------------------------

extern void DigBuf_1_EnableInt(void);
extern void DigBuf_1_DisableInt(void);
extern void DigBuf_1_Start(void);
extern void DigBuf_1_Stop(void);


//--------------------------------------------------
// Constants for DigBuf_1 API's.
//--------------------------------------------------
#define DigBuf_1_CONTROL_REG_START_BIT         ( 0x01 )
#define DigBuf_1_INT_REG_ADDR                  ( 0x0df )
#define DigBuf_1_INT_MASK                      ( 0x01 )


//--------------------------------------------------
// Constants for DigBuf_1 user defined values
//--------------------------------------------------
#pragma ioport  DigBuf_1_DATA_0_REG:    0x040              //DR0 Count register
BYTE            DigBuf_1_DATA_0_REG;
#pragma ioport  DigBuf_1_DATA_1_REG:    0x041              //DR1 Period register
BYTE            DigBuf_1_DATA_1_REG;
#pragma ioport  DigBuf_1_DATA_2_REG:    0x042              //DR2 Compare register
BYTE            DigBuf_1_DATA_2_REG;
#pragma ioport  DigBuf_1_CONTROL_REG:   0x043              //Control register
BYTE            DigBuf_1_CONTROL_REG;
#pragma ioport  DigBuf_1_FUNC_REG:  0x140                  //Function register
BYTE            DigBuf_1_FUNC_REG;
#pragma ioport  DigBuf_1_INPUT_REG: 0x141                  //Input register
BYTE            DigBuf_1_INPUT_REG;
#pragma ioport  DigBuf_1_OUTPUT_REG:    0x142              //Output register
BYTE            DigBuf_1_OUTPUT_REG;
#pragma ioport  DigBuf_1_INT_REG:       0x0df              //Interrupt Mask Register
BYTE            DigBuf_1_INT_REG;


//-------------------------------------------------
// Register Addresses for DigBuf_1
//-------------------------------------------------


//-------------------------------------------------
// DigBuf_1 Macro 'Functions'
//-------------------------------------------------

#define DigBuf_1_Start_M \
   DigBuf_1_CONTROL_REG |=  DigBuf_1_CONTROL_REG_START_BIT

#define DigBuf_1_Stop_M  \
   DigBuf_1_CONTROL_REG &= ~DigBuf_1_CONTROL_REG_START_BIT

#define DigBuf_1_EnableInt_M   \
   M8C_EnableIntMask(DigBuf_1_INT_REG, DigBuf_1_INT_MASK)

#define DigBuf_1_DisableInt_M  \
   M8C_DisableIntMask(DigBuf_1_INT_REG, DigBuf_1_INT_MASK)

#endif
// end of file DigBuf_1.h
