/******************************************************************************
*  Generated by PSoC Designer 5.2.2551
******************************************************************************/
#ifndef __PSOCAPI_H
#define __PSOCAPI_H

#include "PSoCGPIOINT.h"
#include "ADCINC_1.h"
#include "AMUX4_1.h"
#include "DigBuf_1.h"
#include "PGA_1.h"
#include "PWM16_1.h"
#include "PWM8_1.h"
#include "PWM8_2.h"
#include "TX8_1.h"
#include "Timer16_1.h"
#include "Timer16_2.h"

#endif
